### ISSUE TITLE
Convert static site to pelican

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/inpycon2015#1]
This site uses html. We need to convert this to [pelican](http://pelican.readthedocs.org/en/3.5.0/quickstart.html) so that creating blog will be simple as writing markdown and sending pull request.

**Comment by shankisg** [comment]
@kracekumar do you want to convert the full site to pelican or just the blog section.

**Comment by kracekumar** [comment]
Entire site.

On Tue, Feb 17, 2015 at 8:37 AM, shanki notifications@github.com wrote:

> @kracekumar https://github.com/kracekumar do you want to convert the
> full site to pelican or just the blog section.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pythonindia/inpycon2015/issues/1#issuecomment-74610735
> .

## 

Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by shankisg** [comment]
But the landing(home) page shouldn't be converted into pelican. right

**Comment by shankisg** [comment]
One more thing, it is ok re-structure the project, example put all css,js,images into static folder

**Comment by kracekumar** [comment]
Yes, we need to split the html files into templates. Restructuring
shouldn't be an issue.

On Tue, Feb 17, 2015 at 9:13 AM, shanki notifications@github.com wrote:

> One more thing, it is ok re-structure the project, example put all
> css,js,images into static folder
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pythonindia/inpycon2015/issues/1#issuecomment-74613054
> .

## 

Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by shankisg** [comment]
ok great, let me try and get back to you.

**Comment by kracekumar** [comment]
Sure.

On Wed, Feb 18, 2015 at 8:03 AM, shanki notifications@github.com wrote:

> ok great, let me try and get back to you.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pythonindia/inpycon2015/issues/1#issuecomment-74800456
> .

## 

Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by kracekumar** [comment]
It will be nice, if we can get this done by weekend ?

**Comment by shankisg** [comment]
Ok, I planning the same. Do you want to use default theme for blog.

**Comment by kracekumar** [comment]
The theme can be same as current site.

On Fri, Feb 20, 2015 at 5:46 PM, shanki notifications@github.com wrote:

> Ok, I planning the same. Do you want to use default theme for blog.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pythonindia/inpycon2015/issues/1#issuecomment-75229521
> .

## 

Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by shankisg** [comment]
@kracekumar added a pull request.

**Comment by kracekumar** [comment]
Since blog is separate app, this is no more required.
