### ISSUE TITLE
Changing the title does not update the url

### ISSUE THREAD

**Issue by indradhanush** [pythonindia/inpycon2015#13]
Here's a link to my proposal: 
https://in.pycon.org/cfp/pycon-india-2015/proposals/time-travel-with-python/

Initially the title was:
**Time travel with Python**

And I changed it to:
**Avoiding common pitfalls of datetime from a webapp's perpective**

The url remains the same. Shouldn't the url be updated to reflect the new title, while also making sure that the url with the older title redirects to the new one?

**Comment by kracekumar** [comment]
Issue should go to https://github.com/pythonindia/junction. It's a Django
app, it shouldn't be hard for you to fix :-)

On Sun, Jun 28, 2015 at 11:45 PM, Indradhanush Gupta <
notifications@github.com> wrote:

> Here's a link to my proposal:
> 
> https://in.pycon.org/cfp/pycon-india-2015/proposals/time-travel-with-python/
> 
> Initially the title was:
> _Time travel with Python_
> 
> And I changed it to:
> _Avoiding common pitfalls of datetime from a webapp's perpective_
> 
> The url remains the same. Shouldn't the url be updated to reflect the new
> title, while also making sure that the url with the older title redirects
> to the new one?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pythonindia/inpycon2015/issues/13.

## 

Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521
