### ISSUE TITLE
Footer inconsistent

### ISSUE THREAD

**Issue by astronomersiva** [pythonindia/inpycon2015#19]
The picture(the one with temples, Taj and elephants) is present above the footer in the index.html but is missing from the other pages.

Also, was it a design decision to leave the color(#21A7D5) of the picture in the footer different from the color(#49a0d0) of the footer block containing the Python logo? If not, can we make it consistent with the image or in keeping with the gradient oriented design of the site, put a gradient that ranges from the image's blue to the copyright's blue?

![image](https://cloud.githubusercontent.com/assets/7725225/9313914/5fca0e76-4543-11e5-9bc0-94ae2c5703ce.png)

**Comment by kracekumar** [comment]
Can you make the change and post only the screenshot, so I can give feedback ?

**Comment by astronomersiva** [comment]
This is after changing the color of the footer to the color of the image.

![image](https://cloud.githubusercontent.com/assets/7725225/9330412/d9e9486e-45d6-11e5-903a-b55f47e91d0e.png)

This is after applying a gradient. Colors are the color of the image and the color of the design credits block.

![image](https://cloud.githubusercontent.com/assets/7725225/9330522/8f52a7a4-45d7-11e5-821a-f63ac19eb349.png)

**Comment by kracekumar** [comment]
Looks much better. Send a PR.

On Tue, Aug 18, 2015 at 6:33 PM, Sivasubramanyam A <notifications@github.com

> wrote:
> 
> This is after changing the color of the footer to the color of the image.
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/7725225/9330412/d9e9486e-45d6-11e5-903a-b55f47e91d0e.png
> 
> This is after applying a gradient. Colors are the color of the image and
> the color of the design credits block.
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/7725225/9330522/8f52a7a4-45d7-11e5-821a-f63ac19eb349.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pythonindia/inpycon2015/issues/19#issuecomment-132199368
> .

## 

Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by astronomersiva** [comment]
Shall I add the image to the sponsorship, codeofconduct and faq files as well?

They currently look like this:

![image](https://cloud.githubusercontent.com/assets/7725225/9331411/f92a5aa0-45dc-11e5-92f9-16ee92a3dd5f.png)

**Comment by kracekumar** [comment]
Please!

On Tue, Aug 18, 2015 at 7:15 PM, Sivasubramanyam A <notifications@github.com

> wrote:
> 
> Shall I add the image to the sponsorship, codeofconduct and faq files as
> well?
> 
> They currently look like this:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/7725225/9331411/f92a5aa0-45dc-11e5-92f9-16ee92a3dd5f.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pythonindia/inpycon2015/issues/19#issuecomment-132212626
> .

## 

Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521
