### ISSUE TITLE
Buttons improperly aligned at lower screen sizes

### ISSUE THREAD

**Issue by shrayasr** [pythonindia/inpycon2015#3]
![screenshot 2015-02-17 23 03 41](https://cloud.githubusercontent.com/assets/240368/6233506/57f134e6-b6f9-11e4-9296-46172338f37d.png)

and

![screenshot 2015-02-17 23 06 19](https://cloud.githubusercontent.com/assets/240368/6233544/9a25d330-b6f9-11e4-9fd3-4ff904fa258e.png)

---

centre align is required. If we increase the size a little bit more, it looks great.

**Comment by kracekumar** [comment]
Fixed in https://github.com/pythonindia/inpycon2015/commit/7d6fe752b98e971e274bac0cc7b5cc0b49b43efe and
https://github.com/pythonindia/inpycon2015/commit/e3fa1b14de03252379db2e064839b1a282ca4c9a

**Comment by shrayasr** [comment]
:+1:
