### ISSUE TITLE
Blog link updation

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/inpycon2015#7]
When we click on blog link at in.pycon.org/2015/ it take to blog section but we display twitter notification both side.
we need to link it to blog portal  http://in.pycon.org/blog/category/2015.html

**Comment by vnbang2003** [comment]
Have added js file which will get live feed and display.

**Comment by vnbang2003** [comment]
https://github.com/pythonindia/inpycon2015/commit/76f2d26d63abb353c48f28fe1d4d1abe700ee71f
@kracekumar Can we deploy latest code to server.

**Comment by kracekumar** [comment]
Done.
